# Step 1: Build stage
FROM node:20.17.0-alpine3.20 AS build-stage
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Step 2: Production stage
FROM nginxinc/nginx-unprivileged:alpine3.20-perl
USER nginx
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/nginx.conf
COPY  --from=build-stage /app/dist /usr/share/nginx/html
EXPOSE 8080
ENTRYPOINT [ "nginx", "-g", "daemon off;" ]