export const PROFILE_FULL_NAME_MAX_LENGTH = 50;
export const PROFILE_DESCRIPTION_MAX_LENGTH = 250;
export const VIDEO_TITLE_MAX_LENGTH = 100;
export const VIDEO_DESCRIPTION_MAX_LENGTH = 2000;
export const MAX_VIDEO_SIZE_MB = 50;
export const MAX_IMAGE_SIZE_MB = 2;
export const BYTES_IN_MB = 1024 ** 2;
export const VIEW_DURATION_THRESHOLD_SECONDS = 5;
